"""
api/views/pdf_report.py — POST /api/pdf-report/

Takes portfolio data Node already gathered from MongoDB and turns it
into a downloadable PDF using ReportLab. Returns raw PDF bytes
(a plain Django HttpResponse, not a DRF Response) — a PDF isn't JSON,
so there's nothing for DRF's usual renderers to do here.
"""

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from django.http import HttpResponse
from django.utils import timezone
from rest_framework.decorators import api_view

# Brand colors — matches the React app's primary/accent Tailwind shades,
# so the PDF looks like it belongs to the same product instead of a
# generic ReportLab default. Kept as plain hex strings so they can be
# dropped straight into Paragraph markup (colors.HexColor(...) wraps
# them wherever an actual Color object is required, e.g. TableStyle).
BRAND_BLUE = '#2563eb'
LIGHT_BLUE = '#eff6ff'
SLATE = '#475569'
MUTED = '#64748b'
GAIN_GREEN = '#16a34a'
LOSS_RED = '#dc2626'
ZEBRA = '#f8fafc'


def _money(value):
    """Formats a rupee amount as plain text — the ReportLab default font
    (Helvetica) has no glyph for the ₹ symbol, so using it renders as a
    black box instead of a character. 'Rs.' renders correctly with any
    standard font, no need to bundle/register a Unicode font file."""
    return f"Rs. {value:,.0f}"


def _draw_footer(canvas, doc):
    """A thin rule + page number on every page, drawn straight on the canvas
    (Platypus flowables don't repeat automatically per-page on their own)."""
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor(BRAND_BLUE))
    canvas.setLineWidth(0.5)
    canvas.line(1.5 * cm, 1.4 * cm, A4[0] - 1.5 * cm, 1.4 * cm)
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor(SLATE))
    canvas.drawString(1.5 * cm, 1.0 * cm, 'Generated by WealthNest — for personal reference only')
    canvas.drawRightString(A4[0] - 1.5 * cm, 1.0 * cm, f'Page {doc.page}')
    canvas.restoreState()


def build_pdf(family_name, totals, investments):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=1.5 * cm, bottomMargin=2.2 * cm,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
    )
    styles = getSampleStyleSheet()
    elements = []

    section_heading_style = ParagraphStyle(
        'SectionHeading', parent=styles['Heading2'],
        textColor=colors.HexColor(BRAND_BLUE), spaceBefore=4, spaceAfter=8,
    )
    banner_title_style = ParagraphStyle(
        'BannerTitle', parent=styles['Normal'],
        textColor=colors.white, fontName='Helvetica-Bold', fontSize=20, leading=24,
    )
    banner_meta_style = ParagraphStyle(
        'BannerMeta', parent=styles['Normal'],
        textColor=colors.white, fontSize=10, leading=14, alignment=2,  # right-aligned
    )

    # ── Header banner ──
    # A colored letterhead instead of a plain black title — family name
    # and generation date sit on the right, mirroring how a real
    # statement or invoice header is laid out.
    banner_left = Paragraph(
        f'WealthNest<br/><font size=10 color="#dbeafe">Family Investment Portfolio Report</font>',
        banner_title_style,
    )
    banner_right = Paragraph(
        f'Family: <b>{family_name}</b><br/>Generated: {timezone.now().strftime("%d %b %Y, %H:%M")}',
        banner_meta_style,
    )
    banner = Table([[banner_left, banner_right]], colWidths=[11 * cm, 6.5 * cm])
    banner.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(BRAND_BLUE)),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (0, 0), 14),
        ('RIGHTPADDING', (-1, 0), (-1, 0), 14),
        ('TOPPADDING', (0, 0), (-1, -1), 14),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 14),
    ]))
    elements.append(banner)
    elements.append(Spacer(1, 0.8 * cm))

    # ── Summary "stat cards" ──
    # Four side-by-side cells instead of a plain two-column table — the
    # total return cell is colored green/red depending on gain or loss.
    total_return = totals.get('totalReturn', 0)
    return_color = GAIN_GREEN if total_return >= 0 else LOSS_RED

    def stat_cell(label, value, value_color=SLATE):
        return Paragraph(
            f'<font size=9 color="{MUTED}">{label}</font><br/>'
            f'<font size=15 color="{value_color}"><b>{value}</b></font>',
            styles['Normal'],
        )

    stat_row = [[
        stat_cell('TOTAL INVESTED', _money(totals.get('totalInvested', 0))),
        stat_cell('CURRENT VALUE', _money(totals.get('totalValue', 0))),
        stat_cell('TOTAL RETURN', f"{_money(total_return)} ({totals.get('returnPercentage', 0)}%)", return_color),
        stat_cell('INVESTMENTS', str(totals.get('investmentCount', len(investments)))),
    ]]
    stats_table = Table(stat_row, colWidths=[4.375 * cm] * 4)
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(LIGHT_BLUE)),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor(BRAND_BLUE)),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.white),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(stats_table)
    elements.append(Spacer(1, 0.9 * cm))

    # ── Allocation by category ──
    # Groups the same investments by category so the report also answers
    # "how is this split across mutual funds / gold / stocks / etc,"
    # not just "what's the grand total" — the numbers Node already sends
    # per investment are enough to compute this here, no extra data needed.
    elements.append(Paragraph('Allocation by Category', section_heading_style))

    category_totals = {}
    for inv in investments:
        category = inv.get('category', 'other')
        entry = category_totals.setdefault(category, {'invested': 0, 'current': 0})
        entry['invested'] += inv.get('amount', 0)
        entry['current'] += inv.get('currentValue', 0)

    total_current_value = totals.get('totalValue', 0) or 1  # avoid divide-by-zero below
    category_rows = [['Category', 'Invested', 'Current Value', '% of Portfolio']]
    for category, sums in sorted(category_totals.items(), key=lambda kv: kv[1]['current'], reverse=True):
        share = (sums['current'] / total_current_value) * 100
        category_rows.append([
            category.replace('_', ' ').title(),
            _money(sums['invested']),
            _money(sums['current']),
            f"{share:.1f}%",
        ])

    category_table = Table(category_rows, colWidths=[5 * cm, 4.33 * cm, 4.33 * cm, 4.33 * cm])
    category_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(BRAND_BLUE)),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor(ZEBRA)]),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
    ]))
    elements.append(category_table)
    elements.append(Spacer(1, 0.9 * cm))

    # ── Investment details ──
    elements.append(Paragraph('Investment Details', section_heading_style))

    # Plain strings in a ReportLab Table never wrap — a long investment
    # name just overflows into the next column. Wrapping Name/Owner in a
    # Paragraph makes them wrap within their own column width instead.
    cell_style = ParagraphStyle('Cell', parent=styles['Normal'], fontSize=9, leading=11)

    header = ['Name', 'Category', 'Owner', 'Invested', 'Current Value', 'Return']
    rows = [header]
    for inv in investments:
        amount = inv.get('amount', 0)
        current_value = inv.get('currentValue', 0)
        return_pct = ((current_value - amount) / amount * 100) if amount else 0
        rows.append([
            Paragraph(inv.get('name', ''), cell_style),
            (inv.get('category') or '').replace('_', ' ').title(),
            Paragraph(inv.get('owner') or '—', cell_style),
            _money(amount),
            _money(current_value),
            f"{return_pct:+.1f}%",
        ])

    investments_table = Table(rows, colWidths=[4.3 * cm, 2.7 * cm, 2.7 * cm, 2.8 * cm, 2.8 * cm, 2.2 * cm])
    table_style_commands = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(BRAND_BLUE)),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor(ZEBRA)]),
        ('ALIGN', (3, 0), (-1, -1), 'RIGHT'),
    ]
    # Color each row's Return cell green (gain) or red (loss) — same
    # convention as the Investment Detail page in the React app.
    for i, inv in enumerate(investments):
        gained = inv.get('currentValue', 0) >= inv.get('amount', 0)
        table_style_commands.append(('TEXTCOLOR', (5, i + 1), (5, i + 1), colors.HexColor(GAIN_GREEN if gained else LOSS_RED)))
        table_style_commands.append(('FONTNAME', (5, i + 1), (5, i + 1), 'Helvetica-Bold'))

    investments_table.setStyle(TableStyle(table_style_commands))
    elements.append(investments_table)

    doc.build(elements, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    buffer.seek(0)
    return buffer


@api_view(['POST'])
def pdf_report(request):
    family_name = request.data.get('familyName', 'My Family')
    totals = request.data.get('totals', {})
    investments = request.data.get('investments', [])

    pdf_buffer = build_pdf(family_name, totals, investments)

    response = HttpResponse(pdf_buffer.read(), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="wealthnest-portfolio-report.pdf"'
    return response
