/**
 * src/pages/AnalyticsPage.jsx
 *
 * Shows three different visualizations of the same portfolio data,
 * each generated by a different Python library (see
 * django_ai/api/views/analytics.py):
 * - an interactive Plotly chart (react-plotly.js renders Plotly's
 *   JSON output directly — no chart-drawing code needed on this side)
 * - a static Seaborn chart (just a base64 PNG image)
 * - a NetworkX graph of family members <-> investments, shown as a chip grid
 *
 * Plus live market data (Django's web-scraping + REST API endpoint).
 */

import { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import Plot from 'react-plotly.js';
import toast from 'react-hot-toast';

import { getAnalytics, getPortfolioHistory } from '../api/dashboard';
import { getMarketData } from '../api/marketData';
import { selectCurrentUser } from '../redux/slices/authSlice';
import { selectTheme } from '../redux/slices/uiSlice';
import { getPlotlyThemeLayout } from '../utils/plotlyTheme';
import NoFamilyState from '../components/NoFamilyState';
import Avatar from '../components/Avatar';

// Same "no decimals, ₹ symbol" formatting used on Dashboard/Investments —
// duplicated here rather than shared, matching this project's per-file style.
const formatCurrency = (value) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

const AnalyticsPage = () => {
  const user = useSelector(selectCurrentUser);
  const theme = useSelector(selectTheme);
  const [analytics, setAnalytics] = useState(null);
  const [market, setMarket] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Same reasoning as DashboardPage: a user with no family yet would
    // just get "Join a family first" back from the server — expected,
    // not an error worth a toast — so skip the call entirely.
    if (!user?.family) {
      setLoading(false);
      return;
    }

    const load = async () => {
      try {
        const [analyticsRes, marketRes, historyRes] = await Promise.all([
          getAnalytics().catch((err) => {
            toast.error(err.response?.data?.message || 'Could not load analytics');
            return null;
          }),
          getMarketData().catch(() => null), // market data is a nice-to-have — fail silently
          getPortfolioHistory().catch(() => null), // same — a brand-new family just has no history yet
        ]);
        if (analyticsRes) setAnalytics(analyticsRes.data);
        if (marketRes) setMarket(marketRes.data);
        if (historyRes) setHistory(historyRes.data);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [user?.family]);

  if (loading) return <div className="skeleton h-64 w-full rounded-2xl" />;

  if (!user?.family) {
    return <NoFamilyState />;
  }

  const memberNodes = analytics?.familyGraph?.nodes.filter((n) => n.type === 'member') || [];
  const plotlyTheme = getPlotlyThemeLayout(theme);

  return (
    <div className="space-y-6 animate-fade-in">
      <h1 className="section-title">Analytics</h1>

      {!analytics?.categoryChartPlotly ? (
        <div className="card text-center py-12 text-gray-500 dark:text-gray-400">
          Add some investments first to see analytics.
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="card">
            <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-3">Allocation</h2>
            <Plot
              data={analytics.categoryChartPlotly.data}
              layout={{ ...analytics.categoryChartPlotly.layout, ...plotlyTheme, autosize: true, height: 320 }}
              style={{ width: '100%' }}
              config={{ responsive: true, displayModeBar: false }}
            />
          </div>

          <div className="card">
            <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-1">Value by Category</h2>
            <p className="text-xs text-gray-400 dark:text-gray-500 mb-3">Static preview, generated server-side</p>
            {analytics.categoryChartPNG && (
              // Seaborn paints this PNG on a fixed white background
              // server-side — it can't be re-themed from the client, so
              // it gets an explicitly light panel (regardless of app
              // theme) instead of sitting directly on a dark card, which
              // would otherwise look like a rendering bug rather than an
              // intentional "printed chart" treatment.
              <div className="bg-white dark:bg-white rounded-xl p-3 border border-gray-200">
                <img
                  src={`data:image/png;base64,${analytics.categoryChartPNG}`}
                  alt="Portfolio value by category"
                  className="w-full rounded-lg"
                />
              </div>
            )}
          </div>
        </div>
      )}

      {history.length > 1 && (
        <div className="card">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-1">Portfolio Growth Over Time</h2>
          <p className="text-xs text-gray-400 dark:text-gray-500 mb-3">
            One snapshot per day this family's dashboard was viewed — builds up over time.
          </p>
          <Plot
            data={[
              {
                x: history.map((h) => h.snapshotDate.slice(0, 10)),
                y: history.map((h) => h.totalValue),
                type: 'scatter',
                mode: 'lines+markers',
                name: 'Current Value',
                line: { color: '#d4af37' }, // gold — the hero metric on this chart
              },
              {
                x: history.map((h) => h.snapshotDate.slice(0, 10)),
                y: history.map((h) => h.totalInvested),
                type: 'scatter',
                mode: 'lines',
                name: 'Total Invested',
                line: { color: '#64748b', dash: 'dot' },
              },
            ]}
            layout={{ ...plotlyTheme, autosize: true, height: 320, margin: { t: 10, l: 50, r: 10, b: 40 } }}
            style={{ width: '100%' }}
            config={{ responsive: true, displayModeBar: false }}
          />
        </div>
      )}

      {memberNodes.length > 0 && (
        <div className="card">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-3">Family Investment Graph</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">
            Each member's investment count below is how many investments connect to them in the graph.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {memberNodes.map((node) => (
              <div
                key={node.id}
                className="flex items-center gap-3 rounded-xl border border-gray-100 dark:border-dark-700 p-3"
              >
                <Avatar name={node.id} size="md" />
                <span className="font-medium text-gray-800 dark:text-gray-100 truncate flex-1">{node.id}</span>
                <span className="badge-gold shrink-0">
                  {node.degree} investment{node.degree === 1 ? '' : 's'}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {market && (
        <div className="card">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-1">Asset Allocation Tips</h2>
          <p className="text-xs text-gray-400 dark:text-gray-500 mb-3">Scraped live from Wikipedia</p>

          {market.investmentTipsSummary?.length > 0 ? (
            <div className="text-sm text-gray-600 dark:text-gray-300 space-y-2 mb-4">
              {market.investmentTipsSummary.map((para, i) => <p key={i}>{para}</p>)}
            </div>
          ) : (
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Tips are unavailable right now — try again later.</p>
          )}

          <div className="pt-3 border-t border-gray-100 dark:border-dark-700">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-400 dark:text-gray-500 mb-2">
              Live Reference Prices
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div className="rounded-xl bg-gold-50 dark:bg-gold-900/20 p-4">
                <p className="text-sm text-gray-500 dark:text-gray-400">Gold (per oz, INR)</p>
                {market.goldPricePerOunceINR != null ? (
                  <p className="text-lg font-semibold text-gold-700 dark:text-gold-400">
                    {formatCurrency(market.goldPricePerOunceINR)}
                  </p>
                ) : (
                  <p className="text-sm text-gray-400 dark:text-gray-500 mt-1">Price unavailable right now</p>
                )}
              </div>
              <div className="rounded-xl bg-gray-50 dark:bg-dark-700 p-4">
                <p className="text-sm text-gray-500 dark:text-gray-400">Bitcoin (INR)</p>
                {market.bitcoinPriceINR != null ? (
                  <p className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                    {formatCurrency(market.bitcoinPriceINR)}
                  </p>
                ) : (
                  <p className="text-sm text-gray-400 dark:text-gray-500 mt-1">Price unavailable right now</p>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AnalyticsPage;
