/**
 * src/pages/AnalyticsPage.jsx
 *
 * Shows three different visualizations of the same portfolio data,
 * each generated by a different Python library (see
 * django_ai/api/views/analytics.py):
 * - an interactive Plotly chart (react-plotly.js renders Plotly's
 *   JSON output directly — no chart-drawing code needed on this side)
 * - a static Seaborn chart (just a base64 PNG image)
 * - a NetworkX graph of family members <-> investments, shown as a list
 *
 * Plus live market data (Django's web-scraping + REST API endpoint).
 */

import { useEffect, useState } from 'react';
import Plot from 'react-plotly.js';
import toast from 'react-hot-toast';

import { getAnalytics } from '../api/dashboard';
import { getMarketData } from '../api/marketData';

const AnalyticsPage = () => {
  const [analytics, setAnalytics] = useState(null);
  const [market, setMarket] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const [analyticsRes, marketRes] = await Promise.all([
          getAnalytics().catch((err) => {
            toast.error(err.response?.data?.message || 'Could not load analytics');
            return null;
          }),
          getMarketData().catch(() => null), // market data is a nice-to-have — fail silently
        ]);
        if (analyticsRes) setAnalytics(analyticsRes.data);
        if (marketRes) setMarket(marketRes.data);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  if (loading) return <div className="skeleton h-64 w-full rounded-2xl" />;

  const memberNodes = analytics?.familyGraph?.nodes.filter((n) => n.type === 'member') || [];

  return (
    <div className="space-y-6 animate-fade-in">
      <h1 className="section-title">Analytics</h1>

      {!analytics?.categoryChartPlotly ? (
        <div className="card text-center py-12 text-gray-500 dark:text-gray-400">
          Add some investments first to see analytics.
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="card">
            <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-3">Allocation</h2>
            <Plot
              data={analytics.categoryChartPlotly.data}
              layout={{ ...analytics.categoryChartPlotly.layout, autosize: true, height: 320 }}
              style={{ width: '100%' }}
              config={{ responsive: true, displayModeBar: false }}
            />
          </div>

          <div className="card">
            <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-3">Value by Category</h2>
            {analytics.categoryChartPNG && (
              <img
                src={`data:image/png;base64,${analytics.categoryChartPNG}`}
                alt="Portfolio value by category"
                className="w-full rounded-lg"
              />
            )}
          </div>
        </div>
      )}

      {memberNodes.length > 0 && (
        <div className="card">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-3">Family Investment Graph</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">
            Each member's "degree" below is how many investments connect to them in the graph.
          </p>
          <ul className="space-y-1 text-sm">
            {memberNodes.map((node) => (
              <li key={node.id} className="text-gray-700 dark:text-gray-200">
                <span className="font-medium">{node.id}</span> — {node.degree} investment{node.degree === 1 ? '' : 's'}
              </li>
            ))}
          </ul>
        </div>
      )}

      {market && (
        <div className="card">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100 mb-1">Asset Allocation Tips</h2>
          <p className="text-xs text-gray-400 dark:text-gray-500 mb-3">Scraped live from Wikipedia</p>

          {market.investmentTipsSummary?.length > 0 ? (
            <div className="text-sm text-gray-600 dark:text-gray-300 space-y-2 mb-4">
              {market.investmentTipsSummary.map((para, i) => <p key={i}>{para}</p>)}
            </div>
          ) : (
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Tips are unavailable right now — try again later.</p>
          )}

          <div className="pt-3 border-t border-gray-100 dark:border-dark-700">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-400 dark:text-gray-500 mb-2">
              Live Reference Prices
            </p>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-gray-500 dark:text-gray-400">Gold (per oz, INR)</p>
                <p className="text-lg font-semibold">{market.goldPricePerOunceINR ?? '—'}</p>
              </div>
              <div>
                <p className="text-gray-500 dark:text-gray-400">Bitcoin (INR)</p>
                <p className="text-lg font-semibold">{market.bitcoinPriceINR ?? '—'}</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AnalyticsPage;
